//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistics.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDatabaseEntities : DbContext
    {
        public UserDatabaseEntities()
            : base("name=UserDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Level_1> Level_1 { get; set; }
        public virtual DbSet<Level_2> Level_2 { get; set; }
        public virtual DbSet<Level_3> Level_3 { get; set; }
        public virtual DbSet<Level_4> Level_4 { get; set; }
        public virtual DbSet<Level_5> Level_5 { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
